apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/version: master-2019-10-18-d55fee2
  name: thanos-receive-controller
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kubernetes-controller
      app.kubernetes.io/instance: thanos-receive-controller
      app.kubernetes.io/name: thanos-receive-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kubernetes-controller
        app.kubernetes.io/instance: thanos-receive-controller
        app.kubernetes.io/name: thanos-receive-controller
        app.kubernetes.io/version: master-2019-10-18-d55fee2
    spec:
      containers:
      - args:
        - --configmap-name=thanos-receive-controller-tenants
        - --configmap-generated-name=thanos-receive-controller-tenants-generated
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/observatorium/thanos-receive-controller:master-2019-10-18-d55fee2
        imagePullPolicy: IfNotPresent
        name: thanos-receive-controller
        ports:
        - containerPort: 8080
          name: http
        resources: {}
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: thanos-receive-controller
