apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-receive-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: vmaster-2019-10-18-d55fee2
  name: thanos-receive-controller
  namespace: thanos
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: thanos-receive-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos
